### ISSUE TITLE
Env variable without BOREALIS namespace

### ISSUE THREAD

**Issue by guiferrpereira** [OldSneerJaw/heroku-buildpack-borealis-pg-tunnel#1]
Would it be possible to add BOREALIS to all envs that you touch with this addon?

For example we use "API_BASE_URL" that is also being used here and set to empty string.

**Comment by OldSneerJaw** [comment]
Hi, @guiferrpereira. The script in this repo doesn't actually set/overwrite any environment variables. It does set some local and global variables (one of which does have the same name as your `API_BASE_URL` environment variable, admittedly), but the script's variables are all scoped to the script itself and shouldn't impact any environment variables of the same name outside of the script. Regardless, your request has inspired me to change the names of all script variables to `lower_snake_case` so it is visually clear that they are distinct from environment variables, which are usually named as `UPPER_SNAKE_CASE`. The new version of the buildpack ([`v8`](https://github.com/OldSneerJaw/heroku-buildpack-borealis-pg-tunnel/tree/v8)) has been published.

**Comment by guiferrpereira** [comment]
Funny that our ENV variable was being set to empty after we used your addon, we also renamed ours. thanks again for your great work

**Comment by guiferrpereira** [comment]
@OldSneerJaw this shouldn't be updated also: https://github.com/OldSneerJaw/heroku-buildpack-borealis-pg-tunnel/blob/0ecd971baf5a7e1238516b4f353ea78be862939b/profile.d/borealis-pg-init-secure-tunnel.sh#L99

**Comment by OldSneerJaw** [comment]
@guiferrpereira: No, sir. The line you've linked to is not referring to an `API_BASE_URL` variable; rather, it's performing regex pattern matching on part of the value of the `DATABASE_TUNNEL_BPG_CONN_INFO` config variable. That config variable is set by the Borealis Isolated Postgres add-on service with a `KEY1:=VALUE1|KEY2:=VALUE2` format, where the `API_BASE_URL` is simply one of several key-value pairs. The subsequent code extracts a matching substring (the _value_ in the `API_BASE_URL` key-value pair) from that config var to pass as a commandline argument to another script.
